export enum HomePageActionTypes {
    FETCH_MOVEMENTS_BEGIN = 'HOME_PAGE_FETCH_MOVEMENTS_BEGIN',
    FETCH_MOVEMENTS_SUCCESS = 'HOME_PAGE_FETCH_MOVEMENTS_SUCCESS',
    FETCH_MOVEMENTS_FAILED = 'HOME_PAGE_FETCH_MOVEMENTS_FAILED',
    FETCH_CATEGORIES_BEGIN = 'HOME_PAGE_FETCH_CATEGORIES_BEGIN',
    FETCH_CATEGORIES_SUCCESS = 'HOME_PAGE_FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED = 'HOME_PAGE_FETCH_CATEGORIES_FAILED',
    ADD_MOVEMENT = 'HOME_PAGE_ADD_MOVEMENT',
    UPDATE_MOVEMENT = 'HOME_PAGE_UPDATE_MOVEMENT',
    DELETE_MOVEMENT = 'HOME_PAGE_DELETE_MOVEMENT',
    ADD_CATEGORY = 'HOME_PAGE_ADD_CATEGORY',
    DELETE_CATEGORY = 'HOME_PAGE_DELETE_CATEGORY',
};