export enum LoginPageActionTypes {
    LOGIN_BEGIN = 'LOGIN_PAGE_LOGIN_BEGIN',
    LOGIN_SUCCESS = 'LOGIN_PAGE_LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_PAGE_LOGIN_FAILED',
    LOGOUT = 'LOGIN_PAGE_LOGOUT'
};